/*
 * This source file was generated by the Gradle 'init' task
 */
package aplicacion.estudiantes;
import java.util.ArrayList;
import java.util.Scanner;

import static aplicacion.estudiantes.Estudiantes.readEstudiantes;

public class App {      
    
    public ArrayList<Estudiantes> AppEstudiantes(){
        ArrayList<Estudiantes> estudiantes = readEstudiantes();
        return estudiantes;
    }
    
    public void mostrarEstudiantes(ArrayList<Estudiantes> listaEstudiantes) {
        System.out.println("\n--- Todos los Estudiantes ---");
        for (int i = 0; i < listaEstudiantes.size(); i++) {
            System.out.println((i + 1) + ". " + listaEstudiantes.get(i).getNombre() + 
                             " | Edad: " + listaEstudiantes.get(i).getEdad() + 
                             " | Nota: " + listaEstudiantes.get(i).getNotaFinal());
        }
    }
    
    public void mostrarEstudiantesAprobados(ArrayList<Estudiantes> listaEstudiantes) {
        System.out.println("\n--- Estudiantes Aprobados (Nota mayor a 6.0   ) ---");
        boolean hayAprobados = false;
        for (int i = 0; i < listaEstudiantes.size(); i++) {
            if (listaEstudiantes.get(i).getNotaFinal() >= 6.0) {
                System.out.println((i + 1) + ". " + listaEstudiantes.get(i).getNombre() + 
                                 " | Edad: " + listaEstudiantes.get(i).getEdad() + 
                                 " | Nota: " + listaEstudiantes.get(i).getNotaFinal());
                hayAprobados = true;
            }
        }
        if (!hayAprobados) {
            System.out.println("No hay estudiantes aprobados");
        }
    }
    
    public void mostrarMenu(ArrayList<Estudiantes> listaEstudiantes) {
        Scanner scanner = new Scanner(System.in);
        int opcion = 0;
        
        while (opcion != 3) {
            System.out.println("\n--- MENÚ ---");
            System.out.println("1. Mostrar Estudiantes");
            System.out.println("2. Mostrar estudiantes aprobados (Nota mayor a 6.0)");
            System.out.println("3. Salir de la app");
            System.out.print("Selecciona una opción: ");
            
            opcion = scanner.nextInt();
            
            switch (opcion) {
                case 1:
                    mostrarEstudiantes(listaEstudiantes);
                    break;
                case 2:
                    mostrarEstudiantesAprobados(listaEstudiantes);
                    break;
                case 3:
                    System.out.println("\n¡Hasta luego!");
                    break;
                default:
                    System.out.println("Opción inválida, intenta de nuevo");
            }
        }
        scanner.close();
    }
    
    public static void main(String[] args) {
        App app = new App();
        ArrayList<Estudiantes> listaEstudiantes = app.AppEstudiantes();
        
        app.mostrarMenu(listaEstudiantes);
    }
}
